--Initial Starting Point For SQL --
--ALSO to add acoount
DROP DATABASE IF EXISTS yes;
CREATE DATABASE yes;
USE yes;
--LOOK THROUGH DEPARTMENT
DROP TABLE IF EXISTS PRODUCTION
DROP TABLE IF EXISTS TEAMMATE
DROP TABLE IF EXISTS ROLE

CREATE TABLE PRODUCTION (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(30) 

);

CREATE TABLE TEAMMATE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(30) NOT NULL,
)

CREATE TABLE ROLE ID ROLE (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
)